[build]
  publish = "public"
  ignore = "/bin/false"

[functions]
  directory = "netlify/functions" 
  external_node_modules = ["express", "mongoose", "ejs"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
