// create one
POST http://localhost:3001/dialogue
Content-Type: application/json

{
  "startDialogue": "Write it in Nim!",
  "battleDialogue": ["Hello", "World", "I'm jigglipuff"]
}

###

// read all
GET http://localhost:3001/dialogue

###

// read one
GET http://localhost:3001/dialogue/68866598ae7dba730e1d6885

###

// update one
PATCH http://localhost:3001/dialogue/68866598ae7dba730e1d6885
Content-Type: application/json

{
  "startDialogue": "Write it in Nim!",
  "battleDialogue": ["Hello", "World"]
}

###

// delete one
DELETE http://localhost:3001/dialogue/688665a6ae7dba730e1d6887