// create one
POST http://localhost:3001/trainers
Content-Type: application/json

{
  "name": "Dan",
  "codemon": {
    "name": "birb"
  },
  "dialogue": {
    "startBattle": "It's import to keep reminding them that TypeScript has enums."
  }
}

###

// read all
GET http://localhost:3001/trainers

###

// read one
GET http://localhost:3001/trainers/688667ae538c4bf751ef2e5f

###

// update one
PATCH http://localhost:3001/trainers/688667ae538c4bf751ef2e5f
Content-Type: application/json

{
  "name": "Nuc",
  "codemon": {
    "name": "fox"
  },
  "dialogue": {
    "startBattle": "Write it in Nim!"
  }
}

###

// delete one
DELETE http://localhost:3001/trainers/688667a7538c4bf751ef2e5d